### ISSUE TITLE
alpha 3 breaks application

### ISSUE THREAD

**Issue by spruce** [dockyard/ember-validations#297]
I can use alpha 2 within my application. After upgrading to alpha 3 it says it cannot find the method validator in this line:
```
EmberValidations['default'].validator
```
after commenting that out it throws the next error. namely:
```
Error while processing route: verwalten.user Assertion Failed: Expected hash or Mixin instance, got [object Undefined] Error: Assertion Failed: Expected hash or Mixin instance, got [object Undefined]
```

Have you forgotten to export the Mixin?

Linked to #291

**Comment by bcardarella** [comment]
How have you upgraded your ember-cli app. This is a common bug reported for those that have not upgraded their ember-cli properly

**Comment by spruce** [comment]
Had this problem with ember-cli 0.2.0 already. But upgraded to 0.2.3. Have you got a adress where I can find out whether I did a mistake?

**Comment by bcardarella** [comment]
Did you follow all of the proper upgrade instructions? http://www.ember-cli.com/#upgrading

Make note, simply updating the node module is not a proper upgrade

**Comment by spruce** [comment]
Hm. I must have overseen some thing while upgrading. Thanks for the help

**Comment by spruce** [comment]
looks like I didn't upgrade the global ember-cli to 0.2.3. Now everthing works everywhere

**Comment by shiv86** [comment]
Since this is one of the most relevant pages on google search for this particular issue I am just going to comment on it. The current version of ember uses ES6 Modules for importing.

***Current Version Ember***
```
ember version: 1.13.3.
ember-cli: 1.13.1
node: 0.12.6
npm: 2.12.1   
```
Previously I used to import EmberValidations using:

```javascript
import EmberValidations from 'ember-validations;
```
Use it in the following way 

```javascript
export default DS.Model.extend(EmberValidations.Mixin,{
   validations: {
    emailConfirm: EmberValidations.validator(function() {
      if (this.model.get('email') !== this.model.get('emailConfirm')) {
        return "Your emails do not match.";
      }
    }),
}
```

However after the upgrade to the current version (1.13.3) described above I started getting the following error: 
```Expected hash or Mixin instance, got [object Undefined] Error: Assertion Failed: ```

I am guessing this is due to the current version using ES6 Modules importing. So I had to change my code to the following so that I wont get the Assertion Failed error above:

```javascript
import EmberValidations, { validator }  from 'ember-validations';
```


```javascript
/*
Note:
 1. Just using EmberValidations and NOT EmberValidations.Mixin
 2. And Switched to using validator instead of  EmberValidations.validator
 */
export default DS.Model.extend(EmberValidations,{
   validations: {
    emailConfirm: validator(function() {
      if (this.model.get('email') !== this.model.get('emailConfirm')) {
        return "Your emails do not match.";
      }
    })
}
```

References to ES6 Modules:
Since this is one of the most relevant pages on google search for this particular issue I am just going to comment on it. The current version of ember uses ES6 Modules for importing.

***Current Version Ember***
```
ember version: 1.13.3.
ember-cli: 1.13.1
node: 0.12.6
npm: 2.12.1   
```
Previously I used to import EmberValidations using:

```javascript
import EmberValidations from 'ember-validations;
```
Use it in the following way 

```javascript
export default DS.Model.extend(EmberValidations.Mixin,{
   validations: {
    emailConfirm: EmberValidations.validator(function() {
      if (this.model.get('email') !== this.model.get('emailConfirm')) {
        return "Your emails do not match.";
      }
    }),
}
```

However after the upgrade to the current version (1.13.3) described above I started getting the following error: 
```Expected hash or Mixin instance, got [object Undefined] Error: Assertion Failed: ```

I am guessing this is due to the current version using ES6 Modules importing. So I had to change my code to the following so that I wont get the Assertion Failed error above:

```javascript
import EmberValidations, { validator }  from 'ember-validations';
```


```javascript
/*
Note:
 1. Just using EmberValidations and NOT EmberValidations.Mixin
 2. And Switched to using validator instead of  EmberValidations.validator
 */
export default DS.Model.extend(EmberValidations,{
   validations: {
    emailConfirm: validator(function() {
      if (this.model.get('email') !== this.model.get('emailConfirm')) {
        return "Your emails do not match.";
      }
    })
}
```

References to ES6 Modules:


Hope this helps someone in the future!
