### ISSUE TITLE
Observing 'isValid' does not work in a component

### ISSUE THREAD

**Issue by valo** [dockyard/ember-validations#373]
I am having a component which has validations in it and in the parent controller I want to have a property that updates when the `isValid` is updated in the component. Unfortunately using `observes('IsValid')` in the component does not work unless I make a call to `isValid` before that.

I distilled the issue in a jsbin here: http://jsbin.com/rivoke/edit?html,js,output

If you try to enter something for in the `Last name` field you will notice that the name binding is working perfectly, but the validation observer is not firing. If you uncomment the marked line in the `init` method the observe starts working.

Any ideas what could be happening?

**Comment by danmcclain** [comment]
`isValid` is a computed, so it is lazily evaluated. So before the first `get` of `isValid, the value of the computed is not calculated. Observers do not ask for the value to be evaluated, just watch when the value changes

**Comment by valo** [comment]
@danmcclain This makes sense. So it is more of an optimization, than a bug. Any idea if the approach I am taking here is the correct one? Essentially I want to break down a form into separate components with encapsulated validations. An observer on 'isValid' that propagates the value to the parent component was the most obvious thing to do, but I may be missing something.

**Comment by danmcclain** [comment]
Observers are being discouraged for normal use (many side effects and performance implications), with Stef leading the charge: https://www.youtube.com/watch?v=7PUX27RKCq0

If you'd like to encapsulate the validations into other components, I would have the subcomponents "register" themselves with the parent component, that way, inside the parent component you could have a computed property across the `isValid` states of all the subcomponents

Another approach: You could all the validations in the parent form, pass down the form into the separate components. That way you have access to the errors in the separate components to display them, while maintaining the validations on the form itself, allowing `isValid` on the form to be the entire validation state, instead of an aggregate of other components.

**Comment by valo** [comment]
Great suggestions!

> If you'd like to encapsulate the validations into other components, I would have the subcomponents "register" themselves with the parent component, that way, inside the parent component you could have a computed property across the isValid states of all the subcomponents

Is this pattern something that is encouraged as a good practice? I already had to use it in one place and it felt a bit weird and complex.

**Comment by danmcclain** [comment]
I would recommend my second approach over the first, it was more of a suggestion of a way to make your current approach work. Yielding the parent (or what's needed from the parent) is a much better approach

**Comment by valo** [comment]
OK. Unfortunately I will need to use the first approach, as the validation logic is not that simple. There are AJAX calls in there and stuff and I don't want to have coupling between the parent and the child components. Thanks for the pointers! I will close the issue.
