### ISSUE TITLE
Undefined log every time I call validate()

### ISSUE THREAD

**Issue by alexmngn** [DockYard/ember-validations#377]
Hello,
I found out that every time I call the method `validate`, I get the following error in my console:

<img width="692" alt="screen shot 2015-11-22 at 18 49 47" src="https://cloud.githubusercontent.com/assets/4203845/11327097/d581a58c-9149-11e5-93b6-ce8249d585b0.png">

The `errors` property gets populated correctly with the errors.

Not sure what is it, but it looks like something that has been missed in the code of ember-validations.

My code is pretty simple:

```
export default Controller.extend(EmberValidations, {
	validations: {
		'model.firstName': {
			presence: true
		}
	},

	actions: {
		registerClick() {
			this.validate();
		}
	}
}
```
I'm using the version 2.0.0-alpha4

**Comment by BananaNeil** [comment]
A fix should definitely go in for this, but for now, can fix your problem by calling
```
this.validate().then(function(){}).catch(function(){});
```

**Comment by danmcclain** [comment]
You shouldn't be calling validate directly, you should be checking the `isValid` property. Validate is called internally when the properties change

**Comment by alexismangin** [comment]
@danmcclain, maybe the documentation needs to be updated then. It says:

`If you want to force all validations to run simply call .validate()`

```
user.validate().then(function() {
  // all validations pass
  user.get('isValid'); // true
}).catch(function() {
  // any validations fail
  user.get('isValid'); // false
}).finally(function() {
  // all validations complete
  // regardless of isValid state
 user.get('isValid'); // true || false
});
```

**Comment by tsubik** [comment]
Ember treats every rejected promise as an Error and throw it in `onerrordefault` method. I also need to do this nasty trick with swallowing rejection because of failing tests. I would suggest to change `validate`method behaviour to something like that:

```
validate().then((isValid) => {
})
```

Better to leave promise rejections for real errors like failed ajax request for custom validations.

**Comment by bcardarella** [comment]
> Ember treats every rejected promise as an Error

This is incorrect. Only promises used for certain API (and go unhandled) throw an error.

In addition, you should not be using the `validate` function to run validations. They are always being run when values change. Just CP off of the `isValid` flag.

**Comment by tsubik** [comment]
If I reject any `RSVP.Promise` and left it unhandled then Ember throws an error which is I guess good behaviour ([ember twiddle](https://ember-twiddle.com/ad8a90667bfb2adb9986?numColumns=1&openFiles=application.controller.js%2C)). Ok, not using direct `validate` method at all solves the problem. I just had inner array with some `form objects` to validate that's why I was using this. I've created custom validator for arrays and that turns out to be much better approach :smiley:

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
